spring.application.name=MMS
spring.datasource.url=jdbc:mysql://localhost:3306/mmsdb
spring.datasource.username=root
spring.datasource.password=Sakshi@12
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081
jwt.secret=secretkey123456
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gaikwadsakshi374gmail.com
spring.mail.password=Sakshi@123.g
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.securtiy.oauth2.client.registration.google.client-id=195759909993-kgnlhej7mc6isrgq8eo1jp02th5ml4ds.apps.googleusercontent.com
spring.securtiy.oauth2.client.registration.google.client-secret=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
spring.securtiy.oauth2.client.registration.google.scope=openid, profile, email